env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - import
  - prettier
  - react
  - react-hooks
  - jsx-a11y
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
