require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Capybara/FeatureMethods:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
